#pragma once

#define TAPPING_TERM 160
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 6
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_MAX_SPEED 8
#define MOUSEKEY_TIME_TO_MAX 64